{% set name = "py-modelrunner" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-modelrunner-{{ version }}.tar.gz
  sha256: 444334e5b9d27160b1fba7f444537eef26c129b453e86bce859efcbf0ca9fbc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - jinja2 >=3
    - h5py >=3.5
    - numpy >=1.18.0
    - pandas >=1.2
    - pyyaml >=5
    - tqdm >=4.45
    - zarr >=2
    - numcodecs >=0.10

test:
  requires:
    - pip
  imports:
    - modelrunner
  commands:
    - pip check
    # Check whether the pip version is reported correctly
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/zwicker-group/py-modelrunner
  summary: Python classes for organizing (HPC) simulations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - david-zwicker
