{% set name = "py-modelrunner" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df820c05cab790f0d8ecd945317f34d5bea1b2edecb8bc2f097b29435ecbfeac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - jinja2 >=3
    - h5py >=3.5
    - numpy >=1.18.0
    - pandas >=1.2
    - pyyaml >=5
    - tqdm >=4.45
    - zarr >=2,<3
    - numcodecs >=0.10

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - modelrunner
  commands:
    - pip check
    # Check whether the pip version is reported correctly
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/zwicker-group/py-modelrunner
  summary: Python classes for organizing (HPC) simulations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - david-zwicker
